PlaidError: fix bug causing code to always be None
self.code and self.message were being set to the corresponding __init__ parameters after _set_atributes_from_response was called. This was resulting in exceptions created from HTTP responses to have those values set to None.

This factors out self._set_attributes_from_response and instead does that work in init, allowing for clearer handling of code/message init parameters and their precendence over values retrieved from HTTP responses.